version: "3"

services:
  mpi_head:
    build: .
    ports:
      - "2222:22"
    links:
      - mpi_node
    networks:
      - mpi_net

  mpi_node:
    build: .
    networks:
      - mpi_net

networks:
  mpi_net:
    driver: bridge
